import { User } from './user';
export const USERS: User[] = [
  {  name: 'Mr. Nice', checked: false, date: new Date()},
  {  name: 'Narco', checked: false, date: new Date()},
  {  name: 'Bombasto', checked: false, date: new Date() },
  {  name: 'Celeritas', checked: false, date: new Date() },
  {  name: 'Magneta', checked: false, date: new Date() },
  {  name: 'RubberMan', checked: false, date: new Date() },
  {  name: 'Dynama', checked: false, date: new Date() },
  {  name: 'Dr IQ', checked: false, date: new Date() },
  {  name: 'Magma', checked: false, date: new Date() },
  {  name: 'Tornado', checked: false, date: new Date() },
  {  name: 'Mr. Nice', checked: false, date: new Date()},
  {  name: 'Narco', checked: false, date: new Date()},
  {  name: 'Bombasto', checked: false, date: new Date() },
  {  name: 'Celeritas', checked: false, date: new Date() },
  {  name: 'Magneta', checked: false, date: new Date() },
  {  name: 'RubberMan', checked: false, date: new Date() },
  {  name: 'Dynama', checked: false, date: new Date() },
  {  name: 'Dr IQ', checked: false, date: new Date() },
  {  name: 'Magma', checked: false, date: new Date() },
  {  name: 'Tornado', checked: false, date: new Date() },
  {  name: 'Mr. Nice', checked: false, date: new Date()},
  {  name: 'Narco', checked: false, date: new Date()},
  {  name: 'Bombasto', checked: false, date: new Date() },
  {  name: 'Celeritas', checked: false, date: new Date() },
  {  name: 'Magneta', checked: false, date: new Date() },
  {  name: 'RubberMan', checked: false, date: new Date() },
  {  name: 'Dynama', checked: false, date: new Date() },
  {  name: 'Dr IQ', checked: false, date: new Date() },
  {  name: 'Magma', checked: false, date: new Date() },
  {  name: 'Tornado', checked: false, date: new Date() }
];

