import { User } from './user';
import moment from 'moment/src/moment';
export const USERS: User[] = [
  {  name: 'Mr.Nice', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Narco', checked: false, date: new Date(), month:  moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Bombasto', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Celeritas', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Magneta', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'RubberMan', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Dynama', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Dr IQ', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Magma', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Tornado', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Mr. Nice', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Narco', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Bombasto', checked: false, date: new Date() , month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Bombasto', checked: false, date: new Date() , month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Celeritas', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Magneta', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'RubberMan', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Dynama', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Dr IQ', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Magma', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Tornado', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD') },
  {  name: 'Mr. Nice', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD') },
  {  name: 'Narco', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD') },
  {  name: 'Bombasto', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')  },
  {  name: 'Celeritas', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')  },
  {  name: 'Magneta', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD') },
  {  name: 'RubberMan', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')},
  {  name: 'Dynama', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD') },
  {  name: 'Dr IQ', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD') },
  {  name: 'Magma', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')  },
  {  name: 'Magma', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')  },
  {  name: 'Magma', checked: false, date: new Date(), month: moment(new Date(), 'YYYY/MM/DD')  },
];
