import { User } from './user';

export const USERS: User[] = [
  {  name: 'Mr. Nice'},
  {  name: 'Narco'},
  {  name: 'Bombasto' },
  {  name: 'Celeritas' },
  {  name: 'Magneta' },
  {  name: 'RubberMan' },
  {  name: 'Dynama' },
  {  name: 'Dr IQ' },
  {  name: 'Magma' },
  {  name: 'Tornado' },
  {  name: 'Mr. Nice' },
  {  name: 'Narco' },
  {  name: 'Bombasto' },
  {  name: 'Celeritas' },
  {  name: 'Mr. Nice'},
  {  name: 'Narco'},
  {  name: 'Bombasto' },
  {  name: 'Celeritas' },
  {  name: 'Magneta' },
  {  name: 'RubberMan' },
  {  name: 'Dynama' },
  {  name: 'Dr IQ' },
  {  name: 'Magma' },
  {  name: 'Tornado' },
  {  name: 'Mr. Nice' },
  {  name: 'Narco' },
  {  name: 'Bombasto' },
  {  name: 'Celeritas' },
  {  name: 'Celeritas' },
  {  name: 'Mr. Nice'},
  {  name: 'Narco'},
  {  name: 'Bombasto' },
  {  name: 'Celeritas' },
  {  name: 'Magneta' },
  {  name: 'RubberMan' },
  {  name: 'Dynama' },
  {  name: 'Dr IQ' },
  {  name: 'Magma' },
  {  name: 'Tornado' },
  {  name: 'Mr. Nice' },
  {  name: 'Narco' },
  {  name: 'Bombasto' },
];

